name: CI-client
on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt install python2
          sudo apt update
          sudo apt install nodejs
      - name: Build React app
        run: |
          npm install && CI='' npm run build
